version: '3.4'

services:
  web:
    build: .
    container_name: vichan_web
    restart: always
    environment:
      - VIRTUAL_HOST=your_domain.com
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - vichan_network

  db:
    image: mariadb:10.5
    container_name: vichan_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: vichan
      MYSQL_USER: vichan_user
      MYSQL_PASSWORD: vichan_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vichan_network

  nginx:
    image: nginx:latest
    container_name: vichan_nginx
    restart: always
    ports:
      - "8080:80"   # Измените порт на 8080 для HTTP
      - "8443:443"  # Измените порт на 8443 для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - vichan_network

volumes:
  db_data:
    driver: local

networks:
  vichan_network:
    driver: bridge